"""Multi-armed bandit algorithms, experiments, and reporting."""

from .algorithms import (
    BanditAlgorithm,
    BanditStep,
    BayesianUCB,
    DecayingEpsilonGreedy,
    EpsilonGreedy,
    Exp3,
    GradientBandit,
    ThompsonBernoulli,
    UCB1,
    bayesian_ucb,
    decaying_epsilon_greedy,
    epsilon_greedy,
    exp3,
    gradient_bandit,
    thompson_sampling_bernoulli,
    ucb1,
)
from .arms import (
    Arm,
    BernoulliArm,
    GaussianArm,
    arm_from_spec,
    best_arm,
    expected_payoffs,
)
from .experiment import (
    BanditExperiment,
    BanditRunResult,
    available_algorithms,
    run_experiment,
    summarize_runs,
)
from .metrics import (
    arm_selection_counts,
    arm_selection_fractions,
    compare_to_oracle,
    cumulative_regret,
    cumulative_reward,
    regret_curve,
)
from .reporting import render_markdown_report
from .visualization import (
    HAS_MATPLOTLIB,
    plot_arm_selection,
    plot_regret_curves,
    plot_reward_curves,
    save_all_plots,
)

__all__ = [
    "Arm",
    "BernoulliArm",
    "GaussianArm",
    "arm_from_spec",
    "best_arm",
    "expected_payoffs",
    "BanditAlgorithm",
    "BanditStep",
    "EpsilonGreedy",
    "UCB1",
    "ThompsonBernoulli",
    "BayesianUCB",
    "DecayingEpsilonGreedy",
    "GradientBandit",
    "Exp3",
    "epsilon_greedy",
    "ucb1",
    "thompson_sampling_bernoulli",
    "bayesian_ucb",
    "decaying_epsilon_greedy",
    "gradient_bandit",
    "exp3",
    "BanditExperiment",
    "BanditRunResult",
    "available_algorithms",
    "run_experiment",
    "summarize_runs",
    "cumulative_reward",
    "cumulative_regret",
    "regret_curve",
    "compare_to_oracle",
    "arm_selection_counts",
    "arm_selection_fractions",
    "render_markdown_report",
    "HAS_MATPLOTLIB",
    "plot_regret_curves",
    "plot_reward_curves",
    "plot_arm_selection",
    "save_all_plots",
]